# Generate optimization tools for Curry

# Required:
# - root location of the Curry System specified by variable ROOT

.PHONY: all
all:
	@cd binding_optimization && $(MAKE)

.PHONY: clean
clean:
	@cd binding_optimization && $(MAKE) clean
