# Makefile for cleaning analysis files

ANALYSES = $(wildcard *.curry)
CASS     = ../CASS

.PHONY: all compile install clean uninstall

all: compile install

compile: # nothing to do

install: # nothing to do

clean: uninstall
	$(CLEANCURRY)

uninstall: # nothing to do
